import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const lexend_deca = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<SessionProvider session={session}>
			<html lang="en" suppressHydrationWarning={true}>
				<body className={lexend_deca.className}>
					{children}
					<Toaster />
				</body>
			</html>
		</SessionProvider>
	);
}
